export {default as Home} from "./Home"
export {default as Landing} from "./Landing"
export {default as AboutPage} from "./AboutPage"
export {default as ProjectsPage} from "./ProjectsPage"
export {default as ProjectsCategorizedPage} from "./ProjectsCategorizedPage"
export {default as NewsPage} from "./NewsPage"
export {default as SingleNewsPage} from "./SingleNewsPage"