export {default as Home} from "./Home"
export {default as Landing} from "./Landing"
export {default as AboutPage} from "./AboutPage"
export {default as ProjectsPage} from "./ProjectsPage"
export {default as ProjectsCategorizedPage} from "./ProjectsCategorizedPage"
export {default as PrivacyPolicy} from "./PrivacyPolicy"
export {default as OwnerShip} from "./OwnerShip"